### ISSUE TITLE
How would I have submenu close when mouse pointer leaves the element?

### ISSUE THREAD

**Issue by sstudebaker** [iprignano/tendina#10] opened 2015-02-19 17:40 UTC
I have built a menu which is working well except I want the menu to close when not hovered on? Thanks for any help.

**Comment by iprignano** [comment] 2015-02-19 17:47
Hey @sstudebaker,

Your question seems to be a duplicate of issue #3 – you can see how [it has been solved](https://github.com/iprignano/tendina/issues/3#issuecomment-53871518).

I'm closing this, but let me know if I misunderstood your question.

**Closed by iprignano** 2015-02-19 17:47 UTC

**Comment by sstudebaker** [comment] 2015-02-19 18:09
Wow that was fast - So for some reason this didn't work for me. I have a test page up at http://5btech.net/test/

I just want the menu to close when no hovered on but I am missing something... Do you mind taking a look?

**Comment by iprignano** [comment] 2015-02-19 18:20
@sstudebaker,

The JS code bit is actually working – your problem lies in your styles. As [you can see](http://cl.ly/image/3G0z3n2u2H3O/Screen%20Shot%202015-02-19%20at%2019.16.20.png) the menu width is basically 100% of the window width, so you're never leaving the menu with your mouse.

Try to give `.nav-menu` a set width (i.e. 300px) and you'll see it'll work out as expected!

**Comment by sstudebaker** [comment] 2015-02-19 18:23
brilliant - I was starting to think it was something like that because when I moused to the header the dropdown closed :)

THANK YOU
