### ISSUE TITLE
Option to close submenu links when clicking non-submenu link

### ISSUE THREAD

**Issue by kiogo** [iprignano/tendina#9] opened 2014-12-31 20:29 UTC
Hello, great menu. I am needing an option to close any open sub menus when clicking on a first level item which does not have a submenu. Any ideas? Thanks

**Comment by arunabhayani** [comment] 2015-01-01 06:00
Have you tried to implement it? and have you tested demo of tendina? I think its default behavior. no need to set any option for that.

**Comment by kiogo** [comment] 2015-01-01 18:15
Sorry for the wrong title, updated. This is not the default behavior, however the demo does not illustrate this because each menu of the demo has a submenu. If you add a fourth link without a submenu you will see what I am describing. Any previously opened submenus will stay open when clicking a link without a submenu.

**Comment by iprignano** [comment] 2015-01-03 11:20
Hey @kiogo,
the main problem with your question is that Tendina treats menus without children as standard links. So, if you click on a menu like the fourth one in your example, it should redirect you to the given `href`, hence making useless any action after that (i.e. closing other menus).

If you want to have a menu link that doesn't work as a standard link, you'll need to do it without the help of Tendina, since it's not standard behaviour. You'll need to use jQuery's [preventDefault](https://api.jquery.com/event.preventdefault/).

I'm closing this since it's not a bug. Let me know if you think Tendina should have other methods or options!

P.S. Thanks so, so much @arunabhayani for your support! :)

**Closed by iprignano** 2015-01-03 11:20 UTC

**Comment by arunabhayani** [comment] 2015-01-05 10:03
you can do like: 

<li><a href="#" id="menucloses">No Sub Menu</a>

then

 $('#menucloses').on 'click', ->      $('.dropdown').tendina('hideAll')

it will work.
